search-aliases: # Что игроки могут писать вместо /pvp search
  - s # Пример: /pvp s

cancel-aliases: # Аналогично, но только с /pvp cancel
  - c

cooldown: 30 # Как часто (в секундах) можно искать дуэль (на игроков с правом leetpvp.bypass не действует)

enable-effects: true # Выдавать ли игрокам эффекты
effects: # Какие эффекты выдавать игрокам
  - glowing;0;10
  - confusion;0;5

rtp:
  world: world
  distance: 5-20 # На какое расстояние от одного игрока телепортировать другого (по умолчанию от 5 до 20 блоков)
  attempts: 20 # Количество попыток телепортаций
  worldborder: true # Если вас не устраивает РТП в любую точку мира, поставьте false и настройте как вам надо ниже
  center: 0,0 # Координаты x,z центра
  side: 5000 # Длина стороны мира (не путать с радиусом)
  forbidden-blocks: # На какие блоки не телепортировать (все блоки тут https://jd.papermc.io/paper/1.20.6/org/bukkit/block/BlockType.html#field-summary)
    - LAVA
    - WATER

usage:
  - "&cИспользование:"
  - "&b/pvp search &f- найти противника"
  - "&b/pvp cancel &f- отменить поиск"

messages:
  search: "&fВы начали поиск противника. Для отмены напишите &#4bfaa2/pvp cancel"
  already: "&fВы уже ищете противника"
  alert: "&#ed4b1a{player} &fначал искать противника для дуэли. Чтобы сразиться с ним напишите &#ed4b1a/pvp search &fили нажмите сюда"
  cancel: "&fВы отменили поиск дуэли"
  cancel-error: "&cВы и так не ищете дуэль"
  cooldown: "&fПодождите ещё &c{time} секунд &fдля следующего поиска"
  failed: "&fНе получилось найти место для телепортации"

